# file: C:\Users\rudra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\schemathesis\core\failures.py
# hypothesis_version: 6.135.14

['\n    <BINARY>', '\n    <EMPTY>', '\n    <NO RESPONSE>', 'Server error', 'Unknown', 'case_id', 'colno', 'curl', 'deadline', 'document', 'elapsed', 'exception', 'failure', 'lineno', 'message', 'operation', 'origin', 'position', 's', 'severity', 'status', 'status_code', 'title', 'validation_message']