# file: C:\Users\rudra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\schemathesis\engine\errors.py
# hypothesis_version: 6.135.14

[1000, '0x[0-9a-fA-F]+', '0xbaaaaaaaaaad', 'DeadlineExceeded', 'ECONNRESET', 'EngineErrorInfo', 'Failed Health Check', 'Network Error', 'Runtime Error', 'Scalar ', 'Schema Error', 'UnexpectedError', 'Unsupported Schema', '[Errno 104]', '__notes__', 'code_sample', 'connection_other', 'connection_ssl', 'data_too_large', 'error', 'filter_too_much', 'large_base_example', 'network_other', 'schema_generic', 'schema_unsupported', 'too_slow', 'unclassified', 'while generating']