# file: C:\Users\rudra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\graphql\error\located_error.py
# hypothesis_version: 6.135.14

['Node', 'None', 'located_error']